source 'https://rubygems.org'
ruby '2.1.5'
gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'compass-rails', github: 'Compass/compass-rails', branch: 'master' 
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'pry'
gem 'bootstrap-sass', '~> 3.3.4.1'
gem 'devise', '~> 3.4.1'
gem 'devise_invitable', '~> 1.4.2'
gem 'apartment', '~> 1.0.0'
gem 'simple_form'
gem 'launchy', '~> 2.4.3'
gem 'searchkick', '~> 0.8.7'
gem 'acts-as-taggable-on', '~> 3.5.0'
gem 'tinymce-rails'
gem 'jquery-turbolinks'
gem 'paperclip', '~> 4.2'
gem 'cancancan', '~> 1.10.1'
gem 'aws-sdk', '< 2.0'
gem 'jquery-validation-rails'
gem 'htmlbeautifier', '~> 1.1.0'
gem 'chosen-rails'
gem 'jquery-ui-rails'
gem 'sweet-alert'
gem 'sweet-alert-confirm'
gem 'tooltipster-rails'
gem 'listjs-rails'
gem 'chartkick'
gem 'groupdate', '~> 2.4.0'
gem 'bxslider-rails'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'guard'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'letter_opener'
  gem 'bullet', '~> 4.14.7'
end

group :development do
  gem 'brakeman', :require => false
end

group :production do
  gem 'rails_12factor'
  gem 'puma'
end
